[package]
name = "hello_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full", "rt-multi-thread"] }
eframe = "0.28"
egui = "0.28"
egui_extras = "0.28"
egui_plot = "0.28"
csv = "1.2"
plotters = "0.3"
plotters-svg = "0.3"
